name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install PyTorch
      run: |
        pip install torch --index-url https://download.pytorch.org/whl/cpu

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install ./deps/*
        pip install -e .
        pip install pytest

    - name: Run integration tests
      run: |
        python -m pytest tests/ -v
